In [ ]:
import numpy as np

raw_data = "-0.001648 -0.067395 0.997725 -0.000000 -0.999059 0.043353 0.001278 0.000002 -0.043340 -0.996784 -0.067403 -0.000001".split()

raw_extrinsic = [float(p) for p in raw_data]
raw_extrinsic = np.array(raw_extrinsic).reshape(3,4)

quat_data = "-0.000000 0.000002 -0.000001 -0.505569 0.527352 -0.471936 0.493534".split()
quat_data = [float(p) for p in quat_data]

def quaternion_to_rotation_matrix(x, y, z, qx, qy, qz, qw):
    # Normalize the quaternion
    norm = np.sqrt(qx**2 + qy**2 + qz**2 + qw**2)
    qx, qy, qz, qw = qx / norm, qy / norm, qz / norm, qw / norm

    # Compute the rotation matrix
    E_inv = np.zeros((3, 4))
    R = np.array([
        [1 - 2*(qy**2 + qz**2), 2*(qx*qy - qz*qw),     2*(qx*qz + qy*qw)],
        [2*(qx*qy + qz*qw),     1 - 2*(qx**2 + qz**2), 2*(qy*qz - qx*qw)],
        [2*(qx*qz - qy*qw),     2*(qy*qz + qx*qw),     1 - 2*(qx**2 + qy**2)]
    ])

    E_inv[:3, :3] = R
    E_inv[:, 3] = np.array([x, y, z])
    return E_inv

print(quaternion_to_rotation_matrix(*quat_data))
print(raw_extrinsic)

[[-1.64789784e-03 -6.73927537e-02  9.97725163e-01 -0.00000000e+00]
 [-9.99059027e-01  4.33523590e-02  1.27819533e-03  2.00000000e-06]
 [-4.33398806e-02 -9.96784224e-01 -6.74007792e-02 -1.00000000e-06]]
[[-1.64800e-03 -6.73950e-02  9.97725e-01 -0.00000e+00]
 [-9.99059e-01  4.33530e-02  1.27800e-03  2.00000e-06]
 [-4.33400e-02 -9.96784e-01 -6.74030e-02 -1.00000e-06]]


In [4]:
import os
a = "/f/83.png"
os.path.basename(a)

'83.png'